### ISSUE TITLE
NullPointerException when create CodeInputView

### ISSUE THREAD

**Issue by madrojudi** [raycoarana/material-code-input#13]
Hello!
The componant works well for Android version >= 6. But doesn't work for Android version < 6

java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at android.text.StaticLayout.<init>(StaticLayout.java:51)
        at com.raycoarana.codeinputview.CodeInputView.buildErrorTextLayout(CodeInputView.java:343)
        at com.raycoarana.codeinputview.CodeInputView.onMeasure(CodeInputView.java:388)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3076)
        at android.view.View.measure(View.java:18926)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2411)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1429)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1677)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7061)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:822)
        at android.view.Choreographer.doCallbacks(Choreographer.java:606)
        at android.view.Choreographer.doFrame(Choreographer.java:576)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:808)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6917)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by madrojudi** [comment]
It works for the last version (2.1.4)
