### ISSUE TITLE
NullPointerException onDraw

### ISSUE THREAD

**Issue by gewoonwoutje** [raycoarana/material-code-input#4]
It seems like some thread-safety issue.

java.lang.NullPointerException
at com.raycoarana.codeinputview.CodeInputView.onDraw(CodeInputView.java:454)
at android.view.View.draw(View.java:14481)
at android.view.View.getDisplayList(View.java:13378)
at android.view.View.getDisplayList(View.java:13420)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
at android.view.View.getDisplayList(View.java:13316)
at android.view.View.getDisplayList(View.java:13420)
at android.view.View.draw(View.java:14198)
at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
at android.view.View.getDisplayList(View.java:13373)
at android.view.View.getDisplayList(View.java:13420)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
at android.view.View.getDisplayList(View.java:13316)
at android.view.View.getDisplayList(View.java:13420)
at android.view.View.draw(View.java:14198)
at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
at android.view.View.draw(View.java:14484)
at android.view.View.getDisplayList(View.java:13378)
at android.view.View.getDisplayList(View.java:13420)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
at android.view.View.getDisplayList(View.java:13316)
at android.view.View.getDisplayList(View.java:13420)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
at android.view.View.getDisplayList(View.java:13316)
at android.view.View.getDisplayList(View.java:13420)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
at android.view.View.getDisplayList(View.java:13316)
at android.view.View.getDisplayList(View.java:13420)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5033)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:619)
at dalvik.system.NativeStart.main(Native Method)

**Comment by raycoarana** [comment]
Hi, do you have a way to reproduce the crash? Can you share some code? I could be a thread-safety issue yes, but remember that no View in Android do any kind of thread-safety, just crash in case you try to change it in other thread that is not the UI thread. Are your code changing the view in a background thread?

**Comment by gewoonwoutje** [comment]
It's a bit hard to reproduce, because it does not happen always. I did find a workaround: If I explicitly set the length of the code, using
`		codeInputView.setLengthOfCode(5);`
before using 
`		setVisible(VISIBLE);`
fixed the issue.

In the XML file, I set the visibility to GONE per default, and the length_of_code to 5 per default.
```
	<com.raycoarana.codeinputview.CodeInputView
		android:id="@+id/codeInputView"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:layout_marginTop="50dp"
		app:underline_color="@color/skuarioGrey"
		app:underline_selected_color="@color/skuarioGreen"
		app:code_text_color="@color/skuarioGrey"
		app:error_color="@color/skuarioRed"
		app:input_type="numeric"
		app:length_of_code="5"
		android:visibility="gone"
		/>
```
